# Generated by btest

VERSION_STRING = bstatus\ 0.1.0

SHELL = /bin/sh

CFLAGS = -Wall -O2 -g
ALL_CFLAGS = -D BSTATUS_VERSION=\"$(VERSION_STRING)\"

TARGET = bstatus

C_SOURCES = bstatus.c display.c item.c loop.c  log.c config.c configure.c \
            format.c process.c \
            displays/standard.c displays/i3wm.c displays/command.c \
            items/clock.c items/command.c items/cpu.c items/memory.c

TXT_SOURCES = help.txt

MAN_SOURCES = bstatus.1.man bstatus-command.1.man bstatus-sleep.1.man \
              bstatus.conf.5.man

OBJECTS = $(C_SOURCES:.c=.o) $(TXT_SOURCES:.txt=.o)

MAN_PAGES = $(MAN_SOURCES:.man=.gz)

OBJCOPY_ARCH = i386
OBJCOPY_OUTPUT = elf32-i386
ifeq ($(shell uname -m 2>&1), x86_64)
        OBJCOPY_OUTPUT = elf64-x86-64
endif


.SUFFIXES: .c .o .txt .man .gz

all: $(TARGET) bstatus-sleep $(MAN_PAGES)

.c.o:
	$(CC) -c $(CFLAGS) $(ALL_CFLAGS) $< -o $@

.txt.o:
	objcopy -I binary -O $(OBJCOPY_OUTPUT) -B $(OBJCOPY_ARCH) $< $@

.man.gz:
	gzip -c $< > $@

$(TARGET): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

bstatus-sleep: bstatus-sleep.o
	$(CC) $(LDFLAGS) $< -o $@

clean:
	rm -fR $(OBJECTS) $(TARGET) $(MAN_PAGES) \
               bstatus-sleep.o bstatus-sleep build

test: all
	i3bar -b bar-0

install: all
	install -d "$(DESTDIR)/usr/bin/"
	install -d "$(DESTDIR)/etc/"
	install -d "$(DESTDIR)/usr/share/man/man1"
	install -d "$(DESTDIR)/usr/share/man/man5"
	install -m755 bstatus bstatus-command bstatus-sleep \
                      "$(DESTDIR)/usr/bin/"
	install -m644 bstatus.conf "$(DESTDIR)/etc/"
	install -m644 bstatus.1.gz bstatus-command.1.gz bstatus-sleep.1.gz \
                      "$(DESTDIR)/usr/share/man/man1"
	install -m644 bstatus.conf.5.gz "$(DESTDIR)/usr/share/man/man5"
	python3 setup.py install --root="$(DESTDIR)" --optimize=1
